Remove flake9-import-order from lint session
This tool is broken for Python 3.8:

nox > Creating virtual environment (virtualenv) using python3.8 in .nox/lint-3-8
nox > pip install flake8 flake8-bugbear flake8-import-order
nox > flake8 src tests noxfile.py
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/cjolowicz/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/checker.py", line 666, in _run_checks
    return checker.run_checks()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8_import_order/flake8_linter.py", line 91, in run
    for error in self.check_order():
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8_import_order/checker.py", line 55, in check_order
    style_entry_point = self.options['import_order_style']
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/checker.py", line 329, in run
    self.run_parallel()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/hypermodern-python-project/.nox/lint-3-8/lib/python3.8/site-packages/flake8/checker.py", line 293, in run_parallel
    for ret in pool_map:
  File "/Users/cjolowicz/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
TypeError: 'NoneType' object is not subscriptable
nox > Command flake8 src tests noxfile.py failed with exit code 1
nox > Session lint-3.8 failed.